<?php
/** Run only against an isolated database: DB_NAME=questbank_audit_... php tests/verify_exam_workflow.php */
require_once __DIR__.'/../app/bootstrap.php';
require_once __DIR__.'/../app/services/EvaluationService.php';
require_once __DIR__.'/../app/services/AnswerSheetParser.php';
$db = getDBConnection();
if (!str_starts_with($db->query('SELECT DATABASE()')->fetchColumn(), 'questbank_audit_')) throw new RuntimeException('Use an isolated questbank_audit_ database.');
$checks=0;
function check($ok, $label) { global $checks; if (!$ok) throw new RuntimeException('FAIL: '.$label); ++$checks; echo "PASS: $label\n"; }
function denied(callable $fn, string $label) { try {$fn();} catch (LogicException | SecurityException $e) {check(true,$label);return;} throw new RuntimeException('FAIL: '.$label); }
$q=['question_type'=>'problem_solving','correct_answer'=>'4.5','points'=>2];
foreach (['4.5','4.50','x = 4.5',' 4.5 ',"<p>4.50</p>",'4.5e0'] as $a) check(ExamScoringService::evaluateSingleAnswer($q,$a)['awarded_points']===2.0,'Numeric normalization '.json_encode($a));
foreach (['14.5','4.51','-4.5','4.5 or 14.5','NaN','1e999'] as $a) check(ExamScoringService::evaluateSingleAnswer($q,$a)['awarded_points']===0.0,'Reject wrong/ambiguous '.json_encode($a));
check(ExamScoringService::evaluateSingleAnswer($q+['rubric_json'=>'{"steps":true}'],'4.5')['requires_review'],'Rubric requires teacher review');
check(ExamScoringService::evaluateSingleAnswer($q+['partial_credit_enabled'=>1],'4.5')['requires_review'],'Partial-credit work requires teacher review');
check(!ExamScoringService::answersMatch('9007199254740993','9007199254740992'),'Adjacent large integers do not collapse through float rounding');
check(!ExamScoringService::answersMatch('0','0.0000000000000001'),'Tiny nonzero value does not match zero');
check(ExamScoringService::answersMatch('-0.00','0') && ExamScoringService::answersMatch('450e-2','4.50'),'Exact decimal and scientific normalization');
check(ExamScoringService::answersMatch('4.501','4.5',['tolerance'=>0.01]),'Explicit configured numeric tolerance respected');
check(ExamScoringService::evaluateSingleAnswer(['question_type'=>'multiple_choice','correct_answer'=>'Steel','option_a'=>'Steel','option_b'=>'Wood','points'=>1],'A')['awarded_points']===1.0,'Letter response matches option-text key');
check(!ExamScoringService::evaluateSingleAnswer(['question_type'=>'multiple_choice','correct_answer'=>'A','points'=>1],'14.5')['is_correct'],'No numeric normalization of option letters');
foreach (['final','Final','FINALS','finals'] as $term) check(StudentResultService::normalizeTerm($term)==='Finals','Term alias '.$term);
$prefix='audit_'.bin2hex(random_bytes(4));
$ids=[];
foreach (['teacher','student','student','teacher'] as $i=>$role) {
 $stmt=$db->prepare("INSERT INTO users (username,fullname,email,password,role,status,force_password_reset) VALUES (?,?,?,?,?,'active',0)");
 $stmt->execute([$prefix.$i, 'Workflow '.ucfirst($role).' '.$i, $prefix.$i.'@example.test',password_hash('Audit-Only-2026!',PASSWORD_DEFAULT),$role]);
 $ids[]=(int)$db->lastInsertId();
 if($role==='student') $db->prepare("INSERT INTO student_details (user_id,student_number,course,year_level,section) VALUES (?,?,'Audit Engineering','1',?)")->execute([end($ids),$prefix.$i,$prefix]);
}
[$teacher,$student,$otherStudent,$otherTeacher]=$ids;
$create=ExamService::createExam($teacher,'Workflow numeric finals','Audit Mathematics','Structural Engineering',30,[['question_text'=>'Enter the test value.','question_type'=>'problem_solving','correct_answer'=>'4.5','points'=>2]]);
check(!empty($create['success']),'Create exam through existing service');
$exam=(int)$create['exam_id'];
$db->prepare("UPDATE exams SET term='Finals', max_attempts=10, passing_percentage=90 WHERE id=?")->execute([$exam]);
$question=(int)$db->query("SELECT id FROM exam_questions WHERE exam_id=$exam")->fetchColumn();
$db->prepare("UPDATE exam_questions SET explanation='Reference explanation only' WHERE id=?")->execute([$question]);
$res=EvaluationService::evaluateAndSaveSubmission($exam,$student,[$question=>'x = 4.50']);
check(!empty($res['success']),'Typed submission stored');
$submission=(int)$res['submission_id'];
$row=$db->query("SELECT * FROM exam_submissions WHERE id=$submission")->fetch();
check($row['ocr_confidence']===null && $row['extraction_mode']==='not_applicable','Typed answer has no OCR confidence');
$item=ResultWorkflowService::itemResults($submission)[0];
check($item['student_answer']==='x = 4.50' && $item['explanation']==='Reference explanation only','Answer and reference explanation remain separate');
check((float)$item['awarded_points']===2.0,'Stored numeric points are correct');
check(!StudentResultService::results($student),'Finalized private until publication');
denied(fn()=>ResultWorkflowService::transitionStatus($submission,'published',$otherTeacher),'Another teacher cannot publish');
ResultWorkflowService::transitionStatus($submission,'published',$teacher,'Verified final answer');
check(count(StudentResultService::results($student))===1,'Published result in All Terms');
check(count(StudentResultService::results($student,'Finals'))===1,'Published result in Finals');
check(count(StudentResultService::results($student,'final'))===1,'Final alias returns Finals');
check(AuthorizationService::canViewSubmission($student,$submission),'Published resolved record accessible to its student');
$db->prepare('UPDATE submission_answers SET requires_review=1 WHERE submission_id=?')->execute([$submission]);
check(!AuthorizationService::canViewSubmission($student,$submission) && !ResultWorkflowService::enforceStudentPrivacy($submission,$student)['allowed'] && !StudentResultService::results($student),'Legacy published record with unresolved item is private everywhere');
$db->prepare('UPDATE submission_answers SET requires_review=0 WHERE submission_id=?')->execute([$submission]);
check(!StudentResultService::results($student,'Prelim') && !StudentResultService::results($student,'Midterm'),'No cross-term contamination');
check(!ResultWorkflowService::enforceStudentPrivacy($submission,$otherStudent)['allowed'],'Cross-student results denied');
$pub=StudentResultService::publishedSql();
$row=$db->query("SELECT AVG(percentage) avg_score, COUNT(*) completed, AVG(status='Pass')*100 pass_rate FROM exam_submissions es WHERE student_id=$student AND $pub")->fetch();
check((float)$row['avg_score']===100.0 && (int)$row['completed']===1 && (float)$row['pass_rate']===100.0,'Average, completed count and pass rate match records');
$subjects=StudentResultService::subjectPerformance($student);
check(count($subjects)===1 && (float)$subjects[0]['avg_score']===100.0,'Subject mastery is 100 percent');
check(!array_filter($subjects,fn($r)=>(float)$r['avg_score']<StudentResultService::MASTERY_THRESHOLD),'Perfect subject excluded from weak classification');
$res2=EvaluationService::evaluateAndSaveSubmission($exam,$student,[$question=>'4.5 Explanation / Solution: my work']);
$pending=(int)$res2['submission_id'];
check($res2['review_status']==='pending_review','Ambiguous worked solution preserved for review');
check(count(StudentResultService::results($student))===1,'Pending review excluded from results and analytics');
denied(fn()=>ResultWorkflowService::transitionStatus($pending,'published',$teacher),'Cannot publish pending review');
ResultWorkflowService::overrideScore($pending,$question,1,$teacher,'Verified partial written working');
$partial=ResultWorkflowService::itemResults($pending)[0];
check($partial['evaluation_status']==='partial' && (float)$partial['awarded_points']===1.0,'Partial override is not mislabeled fully correct');
ResultWorkflowService::overrideScore($pending,$question,2,$teacher,'Verified full written working');
$item=ResultWorkflowService::itemResults($pending)[0];
check($item['student_answer']==='4.5 Explanation / Solution: my work' && (float)$item['awarded_points']===2.0,'Override preserves submitted work');
$snapshot=json_decode($db->query("SELECT evaluation_result FROM exam_submissions WHERE id=$pending")->fetchColumn(),true)[0];
check((float)$snapshot['awarded_points']===2.0 && !$snapshot['requires_review'],'Override refreshes grading snapshot');
ResultWorkflowService::transitionStatus($pending,'reviewed',$teacher);
ResultWorkflowService::transitionStatus($pending,'finalized',$teacher);
ResultWorkflowService::transitionStatus($pending,'published',$teacher);
check(count(StudentResultService::results($student))===2,'Reviewed result published successfully');
// Unknown confidence needs an explicit human check without inventing a number.
$ocr=ExamScoringService::evaluateAndSaveSubmission($exam,$student,[$question=>'4.5'],$teacher,'scanned',['ocr_text'=>'1. 4.5','ocr_confidence'=>null,'ocr_status'=>'manual_review_required','extraction_mode'=>'image_ocr']);
$ocrId=(int)$ocr['submission_id'];
ResultWorkflowService::transitionStatus($ocrId,'reviewed',$teacher);
denied(fn()=>ResultWorkflowService::transitionStatus($ocrId,'finalized',$teacher),'Uncertain OCR blocks finalization');
ResultWorkflowService::acknowledgeOcrReview($ocrId,$teacher,'Read original sheet and verified answer');
ResultWorkflowService::transitionStatus($ocrId,'finalized',$teacher);
ResultWorkflowService::transitionStatus($ocrId,'published',$teacher);
check($db->query("SELECT ocr_confidence FROM exam_submissions WHERE id=$ocrId")->fetchColumn()===null,'Human OCR review does not fabricate confidence');
// Assignment and archive availability boundaries, with existing history preserved.
$db->prepare('INSERT INTO exam_assignments (exam_id,student_id,assigned_by) VALUES (?,?,?)')->execute([$exam,$student,$teacher]);
check(!ExamService::checkStudentEligibility($otherStudent,$exam)['eligible'],'Unassigned student denied exam access');
$db->prepare("UPDATE exams SET exam_category='qualifying', qualifying_max_attempts=10 WHERE id=?")->execute([$exam]);
check(ExamService::checkStudentEligibility($student,$exam)['eligible'],'Active qualifying exam available');
$before=$db->query("SELECT COUNT(*) FROM submission_answers WHERE exam_id=$exam")->fetchColumn();
ExamService::archiveExam($exam,$teacher);
check(!ExamService::checkStudentEligibility($student,$exam)['eligible'],'Archived qualifying exam is unavailable');
check($db->query("SELECT COUNT(*) FROM submission_answers WHERE exam_id=$exam")->fetchColumn()===$before && count(StudentResultService::results($student))===3,'Archived exam retains answers and published history');
check(!$db->query("SELECT id FROM exams WHERE id=$exam AND status='active' AND exam_category='qualifying'")->fetchColumn(),'Archived parent excluded from active dashboard query');
$parsed=AnswerSheetParser::parseAnswerSheet("--- Page 1 ---\n1. 4.5",[['id'=>$question]]);
check(!$parsed['requires_review'] && $parsed['answers'][$question]==='4.5','OCR parser preserves answer and ignores internal page marker');
// Mixed results exercise actual percentages, per-exam pass thresholds and class grouping.
$low=ExamService::createExam($teacher,'Prelim low mastery','Audit Review Subject','Structural Engineering',30,[['question_text'=>'Numeric value','question_type'=>'identification','correct_answer'=>'2','points'=>1]]);
$lowExam=(int)$low['exam_id'];
$lowQuestion=(int)$db->query("SELECT id FROM exam_questions WHERE exam_id=$lowExam")->fetchColumn();
$lowResult=EvaluationService::evaluateAndSaveSubmission($lowExam,$student,[$lowQuestion=>'9']);
ResultWorkflowService::transitionStatus($lowResult['submission_id'],'published',$teacher);
$mid=ExamService::createExam($teacher,'Midterm configured threshold','Audit Review Subject','Structural Engineering',30,array_fill(0,5,['question_text'=>'Numeric value','question_type'=>'identification','correct_answer'=>'2','points'=>1]));
$midExam=(int)$mid['exam_id'];
$db->exec("UPDATE exams SET term='Midterm', passing_percentage=90 WHERE id=$midExam");
$midQuestions=$db->query("SELECT id FROM exam_questions WHERE exam_id=$midExam ORDER BY id")->fetchAll(PDO::FETCH_COLUMN);
$midAnswers=array_fill_keys($midQuestions,'2');$midAnswers[$midQuestions[4]]='9';
$midResult=EvaluationService::evaluateAndSaveSubmission($midExam,$student,$midAnswers);
ResultWorkflowService::transitionStatus($midResult['submission_id'],'published',$teacher);
check($midResult['percentage']==80 && $midResult['status']==='Fail','80 percent stays failed when exam requires 90 percent');
$peer=EvaluationService::evaluateAndSaveSubmission($midExam,$otherStudent,array_fill_keys($midQuestions,'2'));
ResultWorkflowService::transitionStatus($peer['submission_id'],'published',$teacher);
$all=StudentResultService::results($student);
check(count($all)===5 && count(StudentResultService::results($student,'Finals'))===3 && count(StudentResultService::results($student,'Prelim'))===1 && count(StudentResultService::results($student,'Midterm'))===1,'All three populated term filters have exclusive membership');
check(array_sum(array_column($all,'percentage'))/count($all)===76.0,'Mixed-score average is 76 percent');
check(count(array_filter($all,fn($r)=>$r['status']==='Pass'))/count($all)*100===60.0,'Mixed-score passing rate respects configured thresholds');
$subjectRows=StudentResultService::subjectPerformance($student);
$weak=array_values(array_filter($subjectRows,fn($r)=>(float)$r['avg_score']<StudentResultService::MASTERY_THRESHOLD));
check(count($weak)===1 && $weak[0]['subject']==='Audit Review Subject' && (float)$weak[0]['avg_score']===40.0,'Weak subject has actual 40 percent mastery without duplicating perfect subject');
$stmt=$db->prepare("SELECT AVG(es.percentage) FROM exam_submissions es JOIN student_details sd ON sd.user_id=es.student_id WHERE sd.course='Audit Engineering' AND sd.year_level='1' AND sd.section=? AND $pub");
$stmt->execute([$prefix]);
check((float)$stmt->fetchColumn()===80.0,'Known two-student class average equals 80 percent');
file_put_contents(sys_get_temp_dir().'/questbank-browser-fixture.json',json_encode(['teacher'=>$teacher,'student'=>$student,'otherStudent'=>$otherStudent,'otherTeacher'=>$otherTeacher,'teacher_login'=>$prefix.'0@example.test','student_login'=>$prefix.'1@example.test','exam'=>$exam,'question'=>$question]));
echo "Completed $checks checks. Fixtures retained in isolated database only.\n";
