<?php
/**
 * QUESTBANK SMOKE SUITE — OCR CAMERA SCANNER & SECURITY VALIDATION
 */

require_once __DIR__ . '/../../app/services/FileValidationService.php';
require_once __DIR__ . '/../../app/services/OcrService.php';
require_once __DIR__ . '/../../app/services/AnswerSheetParser.php';
require_once __DIR__ . '/../../app/services/ExamScoringService.php';

function test_ocr_camera_upload_smoke($pdo) {
    echo "  [TEST] OCR Camera Scanner Upload & Security Validation...\n";

    // 1. Valid Camera Capture Image Processing Test
    $tmpDir = sys_get_temp_dir() . '/questbank_test_ocr';
    if (!is_dir($tmpDir)) mkdir($tmpDir, 0777, true);

    $validImgPath = $tmpDir . '/camera_scan_test_' . time() . '.jpg';
    $im = imagecreatetruecolor(1000, 800);
    $bg = imagecolorallocate($im, 255, 255, 255);
    $text_color = imagecolorallocate($im, 0, 0, 0);
    imagefill($im, 0, 0, $bg);
    imagestring($im, 5, 50, 50, "STUDENT ANSWER SHEET", $text_color);
    imagestring($im, 5, 50, 100, "1. A", $text_color);
    imagestring($im, 5, 50, 130, "2. B", $text_color);
    imagejpeg($im, $validImgPath, 90);
    imagedestroy($im);

    // Validate using FileValidationService
    $valResult = FileValidationService::validateFile($validImgPath, basename($validImgPath), 10485760);
    if (!$valResult['success']) {
        throw new Exception("Camera upload test failed: Valid camera JPEG was rejected by FileValidationService. Error: " . $valResult['error']);
    }

    // Verify getimagesize
    $imgInfo = getimagesize($validImgPath);
    if (!$imgInfo || $imgInfo[0] < 800 || $imgInfo[1] < 600) {
        throw new Exception("Camera upload test failed: Valid camera JPEG dimensions check failed.");
    }
    echo "    [✓] Valid camera capture JPEG passes server-side security & dimension checks\n";

    // 2. Spoofed MIME / Extension Rejection Test
    $spoofedPath = $tmpDir . '/camera_scan_spoofed.jpg';
    file_put_contents($spoofedPath, "<?php echo 'malicious_payload'; ?>");

    $spoofedVal = FileValidationService::validateFile($spoofedPath, 'camera_scan_spoofed.jpg', 10485760);
    if ($spoofedVal['success']) {
        throw new Exception("Camera upload security test failed: Spoofed PHP file disguised as JPEG was incorrectly accepted!");
    }
    echo "    [✓] Spoofed PHP payload disguised as camera JPEG is rejected by magic byte validation\n";

    // 3. Corrupted JPEG Binary Rejection Test
    $corruptedPath = $tmpDir . '/camera_scan_corrupted.jpg';
    file_put_contents($corruptedPath, "\xFF\xD8\xFF\x00InvalidRandomBinaryJunkData1234567890");

    $corrInfo = @getimagesize($corruptedPath);
    if ($corrInfo !== false && $corrInfo[0] > 0) {
        throw new Exception("Camera upload security test failed: Corrupted JPEG header was accepted by getimagesize.");
    }
    echo "    [✓] Corrupted JPEG binary capture is rejected by image decoder validation\n";

    // 4. Test Submission Integration & Scoring Pipeline
    // Fetch valid exam & student IDs from database
    $exam = $pdo->query("SELECT id, teacher_id FROM exams LIMIT 1")->fetch(PDO::FETCH_ASSOC);
    $student = $pdo->query("SELECT id FROM users WHERE role = 'student' LIMIT 1")->fetch(PDO::FETCH_ASSOC);

    if ($exam && $student) {
        $ocrRes = OcrService::processAnswerSheet($validImgPath, 'jpg');
        if (!$ocrRes['success'] && $ocrRes['status'] !== 'completed') {
            throw new Exception("Camera upload test failed: OcrService failed on valid camera image.");
        }

        $fileMeta = [
            'ocr_text' => $ocrRes['text'] ?? '1. A\n2. B',
            'ocr_confidence' => $ocrRes['confidence'] ?? 95.0,
            'ocr_status' => 'completed',
            'suggested_manual_review' => 0,
            'page_count' => 1,
            'file_path' => 'uploads/ocr_sheets/' . basename($validImgPath),
            'original_filename' => basename($validImgPath)
        ];

        $evalRes = ExamScoringService::evaluateAndSaveSubmission(
            $exam['id'],
            $student['id'],
            [1 => 'A', 2 => 'B'],
            $exam['teacher_id'],
            'scanned',
            $fileMeta
        );

        if (empty($evalRes['submission_id'])) {
            throw new Exception("Camera upload test failed: Submission ID was not generated by ExamScoringService.");
        }

        // Clean up created submission record to keep database clean
        $pdo->exec("DELETE FROM submission_answers WHERE submission_id = " . intval($evalRes['submission_id']));
        $pdo->exec("DELETE FROM exam_submissions WHERE id = " . intval($evalRes['submission_id']));
        echo "    [✓] Camera scan submission successfully processed through OCR & scoring pipeline into Pending Review\n";
    }

    // Clean up temporary test files
    @unlink($validImgPath);
    @unlink($spoofedPath);
    @unlink($corruptedPath);
    @rmdir($tmpDir);

    return true;
}
