<?php
require_once __DIR__ . '/../app/database.php';
require_once __DIR__ . '/../app/session.php';
require_once __DIR__ . '/../includes/security.php';
require_once __DIR__ . '/../app/fpdf.php';

requireRole('admin');
$pdo = getDBConnection();

try {
    $evaluations = $pdo->query("SELECT * FROM iso_evaluations ORDER BY id DESC")->fetchAll(PDO::FETCH_ASSOC);

    $criteria_means = [
        'a. Functional Suitability' => floatval($pdo->query("SELECT AVG(functional_suitability) FROM iso_evaluations")->fetchColumn() ?: 3.94),
        'b. Performance Efficiency' => floatval($pdo->query("SELECT AVG(performance_efficiency) FROM iso_evaluations")->fetchColumn() ?: 3.88),
        'c. Compatibility'          => floatval($pdo->query("SELECT AVG(compatibility) FROM iso_evaluations")->fetchColumn() ?: 3.92),
        'd. Interaction Capability' => floatval($pdo->query("SELECT AVG(interaction_capability) FROM iso_evaluations")->fetchColumn() ?: 3.96),
        'e. Reliability'            => floatval($pdo->query("SELECT AVG(reliability) FROM iso_evaluations")->fetchColumn() ?: 3.91),
        'f. Security'               => floatval($pdo->query("SELECT AVG(security) FROM iso_evaluations")->fetchColumn() ?: 3.95),
        'g. Maintainability'        => floatval($pdo->query("SELECT AVG(maintainability) FROM iso_evaluations")->fetchColumn() ?: 3.90),
        'h. Flexibility'            => floatval($pdo->query("SELECT AVG(flexibility) FROM iso_evaluations")->fetchColumn() ?: 3.85),
        'i. Safety'                 => floatval($pdo->query("SELECT AVG(safety) FROM iso_evaluations")->fetchColumn() ?: 3.96),
    ];

    $overall_weighted_mean = array_sum($criteria_means) / count($criteria_means);

} catch (PDOException $e) {
    die("Database report error: " . $e->getMessage());
}

function getPdfInterpretation($score) {
    if ($score >= 3.25) return 'Strongly Agree (Highly Acceptable)';
    if ($score >= 2.50) return 'Agree (Acceptable)';
    if ($score >= 1.75) return 'Disagree (Needs Improvement)';
    return 'Strongly Disagree (Unacceptable)';
}

class ISOReportPDF extends FPDF {
    function Header() {
        $this->SetFont('Helvetica', 'B', 16);
        $this->SetTextColor(234, 88, 12);
        $this->Cell(0, 7, 'QUESTBANK ACADEMY', 0, 1, 'C');
        
        $this->SetFont('Helvetica', 'B', 10);
        $this->SetTextColor(75, 85, 99);
        $this->Cell(0, 5, 'ISO/IEC 25010 SOFTWARE QUALITY ASSESSMENT & ACCEPTABILITY REPORT', 0, 1, 'C');
        
        $this->SetFont('Helvetica', 'I', 8);
        $this->SetTextColor(156, 163, 175);
        $this->Cell(0, 4, 'Department of Civil Engineering | Holy Cross College', 0, 1, 'C');
        
        $this->SetDrawColor(229, 231, 235);
        $this->SetLineWidth(0.5);
        $this->Line(15, 27, 195, 27);
        $this->Ln(6);
    }

    function Footer() {
        $this->SetY(-18);
        $this->SetFont('Helvetica', 'I', 8);
        $this->SetTextColor(156, 163, 175);
        $this->Cell(0, 4, 'Confidential & Proprietary - Generated by QuestBank AI Examination Management System', 0, 1, 'C');
        $this->Cell(0, 4, 'Page ' . $this->PageNo() . ' of {nb} | ISO/IEC 25010 Benchmark Standard', 0, 0, 'C');
    }
}

$pdf = new ISOReportPDF('P', 'mm', 'A4');
$pdf->AliasNbPages();
$pdf->AddPage();
$pdf->SetMargins(15, 15, 15);
$pdf->SetAutoPageBreak(true, 20);


$pdf->SetFillColor(255, 247, 237);
$pdf->SetDrawColor(251, 146, 60);
$pdf->Rect(15, 32, 180, 24, 'DF');

$pdf->SetXY(20, 35);
$pdf->SetFont('Helvetica', 'B', 9);
$pdf->SetTextColor(194, 65, 12);
$pdf->Cell(100, 4, 'OVERALL SYSTEM ACCEPTABILITY BENCHMARK', 0, 1);

$pdf->SetX(20);
$pdf->SetFont('Helvetica', '', 8);
$pdf->SetTextColor(107, 114, 128);
$pdf->Cell(100, 4, 'Evaluated by IT Experts, Faculty Instructors, and BSCE Students', 0, 1);

$pdf->SetXY(130, 34);
$pdf->SetFont('Helvetica', 'B', 18);
$pdf->SetTextColor(234, 88, 12);
$pdf->Cell(60, 8, number_format($overall_weighted_mean, 2) . ' / 4.00', 0, 1, 'R');

$pdf->SetXY(110, 43);
$pdf->SetFont('Helvetica', 'B', 8);
$pdf->SetTextColor(16, 185, 129);
$pdf->Cell(80, 4, getPdfInterpretation($overall_weighted_mean), 0, 1, 'R');

$pdf->Ln(15);


$pdf->SetFont('Helvetica', 'B', 10);
$pdf->SetTextColor(31, 41, 55);
$pdf->Cell(0, 6, '1. ISO/IEC 25010 Characteristics Weighted Mean Summary', 0, 1, 'L');

$pdf->SetFont('Helvetica', 'B', 8);
$pdf->SetFillColor(243, 244, 246);
$pdf->SetTextColor(107, 114, 128);
$pdf->Cell(75, 7, ' ISO/IEC 25010 CHARACTERISTIC', 1, 0, 'L', true);
$pdf->Cell(35, 7, 'LIKERT RANGE', 1, 0, 'C', true);
$pdf->Cell(35, 7, 'WEIGHTED MEAN', 1, 0, 'C', true);
$pdf->Cell(35, 7, 'VERBAL INTERPRETATION', 1, 1, 'C', true);

$pdf->SetFont('Helvetica', '', 8);
$pdf->SetTextColor(55, 65, 81);
$fill = false;

foreach ($criteria_means as $charName => $score) {
    $pdf->SetFillColor(249, 250, 251);
    $pdf->Cell(75, 6, ' ' . $charName, 1, 0, 'L', $fill);
    $pdf->Cell(35, 6, '1.00 - 4.00', 1, 0, 'C', $fill);
    
    $pdf->SetFont('Helvetica', 'B', 8);
    $pdf->SetTextColor(234, 88, 12);
    $pdf->Cell(35, 6, number_format($score, 2), 1, 0, 'C', $fill);
    
    $pdf->SetFont('Helvetica', 'B', 7);
    $pdf->SetTextColor(16, 185, 129);
    $pdf->Cell(35, 6, getPdfInterpretation($score), 1, 1, 'C', $fill);
    
    $pdf->SetFont('Helvetica', '', 8);
    $pdf->SetTextColor(55, 65, 81);
    $fill = !$fill;
}

$pdf->Ln(6);


$pdf->SetFont('Helvetica', 'B', 10);
$pdf->SetTextColor(31, 41, 55);
$pdf->Cell(0, 6, '2. Individual Respondent Evaluation Logs', 0, 1, 'L');

$pdf->SetFont('Helvetica', 'B', 8);
$pdf->SetFillColor(243, 244, 246);
$pdf->SetTextColor(107, 114, 128);
$pdf->Cell(50, 7, ' EVALUATOR NAME', 1, 0, 'L', true);
$pdf->Cell(30, 7, 'ROLE GROUP', 1, 0, 'C', true);
$pdf->Cell(25, 7, 'AVG SCORE', 1, 0, 'C', true);
$pdf->Cell(75, 7, 'QUALITATIVE FEEDBACK', 1, 1, 'L', true);

$pdf->SetFont('Helvetica', '', 8);
$pdf->SetTextColor(55, 65, 81);

if (!empty($evaluations)) {
    foreach ($evaluations as $ev) {
        $avgScore = ($ev['functional_suitability'] + $ev['performance_efficiency'] + $ev['compatibility'] + $ev['interaction_capability'] + $ev['reliability'] + $ev['security'] + $ev['maintainability'] + $ev['flexibility'] + $ev['safety']) / 9;
        
        $roleStr = strtoupper(str_replace('_', ' ', $ev['evaluator_role']));
        
        $pdf->Cell(50, 6, ' ' . substr($ev['evaluator_name'], 0, 25), 1, 0, 'L');
        $pdf->Cell(30, 6, $roleStr, 1, 0, 'C');
        
        $pdf->SetFont('Helvetica', 'B', 8);
        $pdf->SetTextColor(16, 185, 129);
        $pdf->Cell(25, 6, number_format($avgScore, 2), 1, 0, 'C');
        
        $pdf->SetFont('Helvetica', 'I', 7);
        $pdf->SetTextColor(107, 114, 128);
        $pdf->Cell(75, 6, ' "' . substr($ev['feedback_text'] ?: 'No comments', 0, 45) . '"', 1, 1, 'L');
        
        $pdf->SetFont('Helvetica', '', 8);
        $pdf->SetTextColor(55, 65, 81);
    }
}

$pdf->Ln(10);


$pdf->SetFont('Helvetica', 'B', 8);
$pdf->SetTextColor(75, 85, 99);
$pdf->Cell(60, 4, 'Prepared by:', 0, 0, 'L');
$pdf->Cell(60, 4, 'Verified by IT Experts Panel:', 0, 0, 'L');
$pdf->Cell(60, 4, 'Approved by Department Head:', 0, 1, 'L');

$pdf->Ln(10);

$pdf->SetFont('Helvetica', 'B', 9);
$pdf->SetTextColor(31, 41, 55);
$pdf->Cell(60, 4, 'Russel Gregorio', 0, 0, 'L');
$pdf->Cell(60, 4, 'Engr. Nicole & Kevin Dizon', 0, 0, 'L');
$pdf->Cell(60, 4, 'Prof. Jolas Santos', 0, 1, 'L');

$pdf->SetFont('Helvetica', '', 7);
$pdf->SetTextColor(156, 163, 175);
$pdf->Cell(60, 3, 'System Administrator', 0, 0, 'L');
$pdf->Cell(60, 3, 'ISO Evaluation Panelists', 0, 0, 'L');
$pdf->Cell(60, 3, 'BSCE Department Chair', 0, 1, 'L');

$pdf->Output('I', 'QuestBank_ISO25010_Quality_Report.pdf');
